apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-storage-classes2
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: cluster-config
  source:
    path: components/apps/cluster-config/storage-classes2
    repoURL: https://github.com/ahusssain/cluster-config
    targetRevision: testing
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
