apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ovirt-csi-silver2
parameters:
  storageDomainName: hosted_storage
  thinProvisioning: "true"
provisioner: csi.ovirt.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
